# Generated by Django 6.0 on 2025-09-07 19:37

import api.model.UserProfileModel
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofiles_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='document',
            name='semester',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessioncode',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sessioncode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sessioncode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sessioncode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.model.UserProfileModel.user_profile_picture_path, validators=[api.model.UserProfileModel.validate_image_size]),
        ),
    ]
