# Generated by Django 6.0 on 2025-09-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_options_alter_userprofiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
