# Generated by Django 6.0 on 2025-09-08 18:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(resource_type='raw'), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
