# Generated by Django 6.0 on 2025-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_document_file_alter_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('doc', 'doc'), ('docx', 'docx'), ('txt', 'txt'), ('ppt', 'ppt'), ('pptx', 'pptx'), ('zip', 'zip'), ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('png', 'png'), ('gif', 'gif'), ('webp', 'webp'), ('xls', 'xls'), ('xlsx', 'xlsx'), ('csv', 'csv')], max_length=20),
        ),
    ]
