# Generated by Django 6.0 on 2025-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('zip', 'ZIP'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('webp', 'WEBP'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=20),
        ),
    ]
