# Generated by Django 6.0 on 2025-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
    ]
