# Generated by Django 6.0 on 2025-09-11 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_document_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='Easy', max_length=32)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('points', models.IntegerField(default=5)),
                ('starter_code', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='branch',
            field=models.CharField(default='Default Branch', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='college',
            field=models.CharField(default='General', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('zip', 'ZIP'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('webp', 'WEBP'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='resource_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='semester',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('passed', models.BooleanField(default=False)),
                ('passed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('details', models.JSONField(default=list)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='api.problem')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
